// Generated by gencpp from file camera_module/camera_orientation.msg
// DO NOT EDIT!


#ifndef CAMERA_MODULE_MESSAGE_CAMERA_ORIENTATION_H
#define CAMERA_MODULE_MESSAGE_CAMERA_ORIENTATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace camera_module
{
template <class ContainerAllocator>
struct camera_orientation_
{
  typedef camera_orientation_<ContainerAllocator> Type;

  camera_orientation_()
    : x(0)
    , y(0)  {
    }
  camera_orientation_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef uint8_t _x_type;
  _x_type x;

   typedef uint8_t _y_type;
  _y_type y;




  typedef boost::shared_ptr< ::camera_module::camera_orientation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera_module::camera_orientation_<ContainerAllocator> const> ConstPtr;

}; // struct camera_orientation_

typedef ::camera_module::camera_orientation_<std::allocator<void> > camera_orientation;

typedef boost::shared_ptr< ::camera_module::camera_orientation > camera_orientationPtr;
typedef boost::shared_ptr< ::camera_module::camera_orientation const> camera_orientationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::camera_module::camera_orientation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::camera_module::camera_orientation_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace camera_module

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'camera_module': ['/home/ahlab/AirTurtle/basic_functionalities/camera_module/src/camera_module/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::camera_module::camera_orientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::camera_module::camera_orientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_module::camera_orientation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::camera_module::camera_orientation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_module::camera_orientation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::camera_module::camera_orientation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::camera_module::camera_orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "727012f6868afa655d78dc8b436d2c91";
  }

  static const char* value(const ::camera_module::camera_orientation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x727012f6868afa65ULL;
  static const uint64_t static_value2 = 0x5d78dc8b436d2c91ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera_module::camera_orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "camera_module/camera_orientation";
  }

  static const char* value(const ::camera_module::camera_orientation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::camera_module::camera_orientation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 x\n\
uint8 y\n\
#x base rotation\n\
#y camera inclination\n\
\n\
";
  }

  static const char* value(const ::camera_module::camera_orientation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::camera_module::camera_orientation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct camera_orientation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera_module::camera_orientation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::camera_module::camera_orientation_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CAMERA_MODULE_MESSAGE_CAMERA_ORIENTATION_H
